# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "university-assignment"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = []
license = "MIT"
description = "A clean and simple template for university assignments."
repository = "https://github.com/UtkarshVerma/typst-university-assignment"
keywords = ["university", "assignment"]
categories = ["report"]
disciplines = []
compiler = ""
exclude = [".github", "docs", "scripts", "tests", ".typstignore", "Justfile"]

[template]
path = "src/template"
entrypoint = "src/template/main.typ"
thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
